#! /bin/sh
#
#  File - run
#
#  Purpose - Test ofp.
#
#  Author - Andrew Halper <ashalper@usgs.gov>
#

python \
  -u ../pkg/climate_etl.py -t date \
  -p 2019-08-21 2019-08-22 -i $HOME/workspace/nhm/nhm_hru_data \
  -o $HOME/workspace/nhm/NHM-PRMS_CONUS/input \
  -w $HOME/workspace/nhm/nhm_hru_data/weights.csv
